name: doctor_appointment_booking
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  easy_localization: ^2.3.3
  rflutter_alert: ^1.1.0
  sleek_circular_slider:
  share: ^0.6.5+4
  qr_code_scanner: ^0.2.1
  cached_network_image: ^2.3.3
  shape_of_view: ^1.0.2
  flutter_page_indicator: ^0.0.3
  image_picker: ^0.6.7+12
  flutter_bloc: ^6.0.6
  responsive_framework: ^0.0.11
  equatable: ^1.2.5
  percent_indicator: ^2.1.8
  flutter_statusbarcolor: ^0.2.3
  url_launcher: ^5.7.10
  flutter_mailer:
  otp_text_field: ^1.0.1
  fluttertoast: ^7.1.8
  shared_preferences: ^0.5.12+4
  sign_in_with_apple: ^2.5.4
  firebase_auth: ^0.16.0
  google_sign_in: ^4.4.4
  sqflite: ^1.3.2+1
  path_provider: ^1.6.24
  intl:
  apple_sign_in: ^0.1.0
  flutter_auth_buttons: ^0.10.0
  flutter_share: ^1.0.5
  file_picker: ^2.1.6
  permission_handler: ^5.1.0+2


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^2.1.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/languages/
    - assets/images/intro_1.png
    - assets/images/google-logo.png
    - assets/images/intro_2.png
    - assets/images/intro_3.png
    - assets/images/myazlogo.png
    - assets/images/slide.png
#    - assets/locale/

  fonts:
    - family: Literata
      fonts:
        - asset: assets/fonts/Literata.ttf
        - asset: assets/fonts/Literata-Italic.ttf
flutter_icons:
  android: "launcher_icon"

  ios: true
  image_path: "assets/images/logoo.png"






